"""add user_info table

Revision ID: 110375b57c4c
Revises: 
Create Date: 2024-12-20 11:24:27.805005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '110375b57c4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('signature', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', 'unknown', name='sex'), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_info'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###
